export const ACCOUNT_TYPES = [
  {
    value: "individual",
    label: "Individual Creator (TikTok, X, YouTube, etc.)",
  },
  { value: "newsletter", label: "Newsletter / Blog" },
  { value: "community", label: "Community / Discord / Telegram" },
  { value: "other", label: "Other" },
] as const;

export const MAIN_AUDIENCES = [
  "TikTok",
  "X (Twitter)",
  "YouTube",
  "Instagram / Reels",
  "Newsletter",
  "Discord / Telegram",
  "Blog / Website",
  "Other",
] as const;

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
  "Italian",
  "Dutch",
  "Arabic",
  "Hindi",
  "Japanese",
  "Korean",
  "Chinese",
  "Other",
] as const;

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Italy",
  "Brazil",
  "Mexico",
  "India",
  "Japan",
  "South Korea",
  "Singapore",
  "United Arab Emirates",
  "Nigeria",
  "South Africa",
  "Philippines",
  "Indonesia",
  "Turkey",
  "Poland",
  "Sweden",
  "Norway",
  "Denmark",
  "Switzerland",
  "Belgium",
  "Austria",
  "Ireland",
  "New Zealand",
  "Portugal",
  "Argentina",
  "Colombia",
  "Chile",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Pakistan",
  "Egypt",
  "Kenya",
  "Other",
] as const;
